
[connections.postgresql]
dialect = "postgresql"
host = "localhost"
port = "5432"
database = "postgres"
username = "postgres"
password = "Azerty123!!!"


[connections.postgresql_container]
dialect = "postgresql"
host = "db"
port = "5432"
database = "postgres"
username = "postgres"
password = "Azerty123!!!"